# Generated by Django 5.2 on 2025-05-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaproject',
            name='area',
        ),
        migrations.RemoveField(
            model_name='areaproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_type',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='project',
        ),
        migrations.RemoveField(
            model_name='toolproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='toolproject',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='workgroupuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workgroupuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='AreaProject',
        ),
        migrations.DeleteModel(
            name='PermissionType',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='StatusType',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='RoleType',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='ToolProject',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WorkGroup',
        ),
        migrations.DeleteModel(
            name='WorkGroupUser',
        ),
    ]
