# Generated by Django 5.2 on 2025-05-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
        migrations.AlterModelTable(
            name='userareapermissions',
            table='user_area_permissions',
        ),
        migrations.AlterModelTable(
            name='usergrouppermissions',
            table='user_group_permissions',
        ),
        migrations.AlterModelTable(
            name='userprojectpermissions',
            table='user_project_permissions',
        ),
        migrations.AlterModelTable(
            name='userrepositorypermissions',
            table='user_repository_permissions',
        ),
        migrations.AlterModelTable(
            name='usertoolpermissions',
            table='user_tool_permissions',
        ),
    ]
