# Generated by Django 5.2 on 2025-05-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permissions', '0002_alter_permission_table_and_more'),
        ('users', '0002_alter_roletype_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergrouppermissions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergrouppermissions',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergrouppermissions',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='usergrouppermissions',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userprojectpermissions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprojectpermissions',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userprojectpermissions',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprojectpermissions',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrepositorypermissions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrepositorypermissions',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userrepositorypermissions',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='userrepositorypermissions',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usertoolpermissions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertoolpermissions',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='usertoolpermissions',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='usertoolpermissions',
            name='user',
        ),
        migrations.CreateModel(
            name='UserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_object_permissions',
                'unique_together': {('user', 'permission', 'content_type', 'object_id')},
            },
        ),
        migrations.DeleteModel(
            name='UserAreaPermissions',
        ),
        migrations.DeleteModel(
            name='UserGroupPermissions',
        ),
        migrations.DeleteModel(
            name='UserProjectPermissions',
        ),
        migrations.DeleteModel(
            name='UserRepositoryPermissions',
        ),
        migrations.DeleteModel(
            name='UserToolPermissions',
        ),
    ]
