# Generated by Django 5.2 on 2025-05-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permissions', '0003_alter_usergrouppermissions_unique_together_and_more'),
        ('users', '0003_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_model_permissions',
                'unique_together': {('user', 'permission', 'content_type')},
            },
        ),
    ]
