# Generated by Django 5.2 on 2025-05-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workgroup',
            table='work_groups',
        ),
        migrations.AlterModelTable(
            name='workgroupmembership',
            table='work_groups_memberships',
        ),
    ]
