# Generated by Django 5.2 on 2025-05-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repository',
            table='repositories',
        ),
    ]
