# Generated by Django 5.2 on 2025-05-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tool',
            table='tools',
        ),
        migrations.AlterModelTable(
            name='toolproject',
            table='tools_projects',
        ),
    ]
