# Generated by Django 5.2 on 2025-05-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_table_alter_toolproject_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(upload_to='tools_images/'),
        ),
    ]
